WITHOUT THE PIPELINES

In [ ]:
# required data preprocessing libraries

import pandas as pd
import numpy as np


In [ ]:
da = pd.read_csv('train.csv')                     #infamous -titanic data

In [ ]:
da.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [ ]:
da.drop(columns =['Name' , 'Ticket' , 'Cabin' , 'PassengerId'] , inplace = True)               #inplace = True eliminates the need of modifying means otherwise we need to assign the changes
#  to a new variable like new_da = .....


In [ ]:
da.head()

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

STEP - I

In [ ]:
from sklearn.model_selection import train_test_split

x_train , x_test , y_train , y_test = train_test_split(da.drop(columns = ['Survived']) , da['Survived'] , random_state = 42 , test_size = 0.2) #20%891 in testing - 178

# survived will be in o/p

In [ ]:
x_train.head()

Pclass     Sex   Age  SibSp  Parch     Fare Embarked
331       1    male  45.5      0      0  28.5000        S
733       2    male  23.0      0      0  13.0000        S
382       3    male  32.0      0      0   7.9250        S
704       3    male  26.0      1      0   7.8542        S
813       3  female   6.0      4      2  31.2750        S

In [ ]:
y_train.head()

331    0
733    0
382    0
704    0
813    0
Name: Survived, dtype: int64

In [ ]:
da.isnull().sum()                      #check the missing value in all columns  - found the Embarked and age

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64

In [ ]:
from sklearn.impute import SimpleImputer                   # to handle a missing data in a dataset

si_Age = SimpleImputer()
si_Embarked = SimpleImputer(strategy = 'most_frequent')                              # strategy means the method used to fill (impute) missing values.
# as here the Embarked is string we have taken mode otherwise by default it we will be taken as the mean not suitable for naN value to be filled out so used the mode and here it is S
# so msiising value get filled with the S(i.e 2values)

x_train_age_imp = si_Age.fit_transform(x_train[['Age']])
x_train_Embarked_imp = si_Embarked.fit_transform(x_train[['Embarked']])

# only transform
x_test_age_imp = si_Age.transform(x_test[['Age']])
x_test_Embarked_imp = si_Embarked.transform(x_test[['Embarked']])

In [ ]:
x_train_age_imp
x_train_Embarked_imp

array([['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['C'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['C'],
       ['S'],
       ['Q'],
       ['Q'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['Q'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['Q'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
      

In [ ]:
x_test_Embarked_imp

array([['C'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['Q'],
       ['S'],
       ['Q'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['Q'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['Q'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['Q'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['Q'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['Q'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['Q'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['C'],
       ['S'],
      

In [ ]:
da['Embarked'].unique()

array(['S', 'C', 'Q', nan], dtype=object)

STEP - II

In [ ]:
from sklearn.preprocessing import OneHotEncoder              #now for the categorical datasets -_-

# so for colums - Sex & Embarked
ohe_Sex = OneHotEncoder(sparse_output=False, handle_unknown= 'ignore')              # By default, OneHotEncoder returns a sparse matrix to save memory  but sparse=False,
# it returns a regular NumPy array (dense matrix)

ohe_Embarked = OneHotEncoder(sparse_output=False , handle_unknown = 'ignore')

# handle_unknown='ignore' This handles the case when, during prediction or transformation, the data has a category that the encoder didn’t see during training (fit)
# If don’t set this, it will give an error for unknown categories.  , like in training set it might not see that particular variabel not see it in the testset
# With handle_unknown='ignore', the encoder skips that unknown value and fills it with all zeros .

In [ ]:
x_train_Sex = ohe_Sex.fit_transform(x_train[['Sex']])
x_train_Embarked = ohe_Embarked.fit_transform(x_train_Embarked_imp)

x_test_Sex = ohe_Sex.transform(x_test[['Sex']])
x_test_Embarked = ohe_Embarked.transform(x_test_Embarked_imp)

In [ ]:
x_train_Sex   # two - male and female

array([[0., 1.],
       [0., 1.],
       [0., 1.],
       ...,
       [0., 1.],
       [1., 0.],
       [0., 1.]])

In [ ]:
x_train_Embarked       # three - S C Q

array([[0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       ...,
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.]])

In [ ]:
# now three arrays has been created for sex embarked and age

x_train_rem = x_train.drop(columns = ['Sex' , 'Embarked' , 'Age'])
x_test_rem = x_test.drop(columns = ['Sex' , 'Embarked' , 'Age'])
# this is for the rem cols means ie.4cols

In [ ]:
x_train_rem

Pclass  SibSp  Parch      Fare
331       1      0      0   28.5000
733       2      0      0   13.0000
382       3      0      0    7.9250
704       3      1      0    7.8542
813       3      4      2   31.2750
..      ...    ...    ...       ...
106       3      0      0    7.6500
270       1      0      0   31.0000
860       3      2      0   14.1083
435       1      1      2  120.0000
102       1      0      1   77.2875

[712 rows x 4 columns]

In [ ]:
x_train_trans = np.concatenate(  (x_train_rem , x_train_Sex , x_train_Embarked , x_train_age_imp ) , axis = 1)
x_test_trans = np.concatenate(    (x_test_rem , x_test_Sex , x_test_Embarked  , x_test_age_imp ) , axis = 1)

#  axis=1 Join arrays column-wise i.e., side by side

In [ ]:
x_train_trans

array([[ 1. ,  0. ,  0. , ...,  0. ,  1. , 45.5],
       [ 2. ,  0. ,  0. , ...,  0. ,  1. , 23. ],
       [ 3. ,  0. ,  0. , ...,  0. ,  1. , 32. ],
       ...,
       [ 3. ,  2. ,  0. , ...,  0. ,  1. , 41. ],
       [ 1. ,  1. ,  2. , ...,  0. ,  1. , 14. ],
       [ 1. ,  0. ,  1. , ...,  0. ,  1. , 21. ]])

In [ ]:
x_test_trans.shape

(179, 10)

In [ ]:
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier()

In [ ]:
clf.fit(x_train_rem , y_train)

# trains (fits) the decision tree model using training data

DecisionTreeClassifier()

In [ ]:
y_pred =  clf.predict(x_test_rem)
# uses the trained model (clf) to make predictions on the test data.

In [ ]:
y_pred

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 1])

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test , y_pred)

0.6927374301675978

In [ ]:
import pickle         #pickle helps save Python objects (like models) as files

pickle.dump(ohe_Sex ,open('ohe_sex.pkl' , 'wb'))

# Saves  one-hot encoder for 'Sex' (ohe_sex) into a file.
# 'ohe_sex.pkl': path and filename where it's saved.
#'wb': means write in binary mode (needed for pickle files)

pickle.dump(ohe_Embarked , open('ohe_embarked.pkl' , 'wb'))

pickle.dump(clf , open('clf.pkl' , 'wb'))
# This saves trained decision tree model (clf) into a file