In [ ]:
print('Namaste')


Namaste


In [ ]:
import numpy as np
import pandas as pd

In [ ]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.impute import SimpleImputer

In [ ]:
df = pd.read_csv('covid_toy.csv')

In [ ]:
df.head()

age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [ ]:
print(df['city'].value_counts())
df['city'].is_unique

city
Kolkata      32
Bangalore    30
Delhi        22
Mumbai       16
Name: count, dtype: int64


False

In [ ]:
df['cough'].value_counts()

cough
Mild      62
Strong    38
Name: count, dtype: int64

In [ ]:
df['city'].nunique()

4

In [ ]:
# check if any value is missing or not
df.isnull().sum()

NameError: name 'df' is not defined

In [ ]:
# before tranformation train_test_split
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(df.drop(columns=['has_covid']) , df['has_covid'] , test_size=0.2 , random_state=1)


In [ ]:
x_train             # 80% of 100 - 80 entries

age  gender  fever   cough       city
2    42    Male  101.0    Mild      Delhi
73   34    Male   98.0  Strong    Kolkata
97   20  Female  101.0    Mild  Bangalore
62   56  Female  104.0  Strong  Bangalore
19   42  Female    NaN  Strong  Bangalore
..  ...     ...    ...     ...        ...
75    5    Male  102.0    Mild    Kolkata
9    64  Female  101.0    Mild      Delhi
72   83  Female  101.0    Mild    Kolkata
12   25  Female   99.0  Strong    Kolkata
37   55    Male  100.0    Mild    Kolkata

[80 rows x 5 columns]

In [ ]:
# SimpleImputer is applied for the fever column , as it's used for handling missing values
si = SimpleImputer()
x_train_fever = si.fit_transform(x_train[['fever']])
x_test_fever = si.transform(x_test[['fever']])
x_train_fever.shape

(80, 1)

In [ ]:
# OneHotEnconding for gender and city as it converts nominal data into the vectors form
# for gender we have - 2cols i.e male&female means only one will be taken & form  city we have 4 so 3 will be taken
# why ? becasue of the multicollinearity , so in total there are 4 cols

ohe = OneHotEncoder(drop= 'first' , sparse_output =False)
# drop the one_col from each category and sparse_output returns a regular NumPy array instead of a sparse matrix


x_train_gender_city = ohe.fit_transform(x_train[['gender','city']])
x_test_gender_city  = ohe.transform(x_test[['gender','city']])

print(x_train_gender_city .shape)
x_train_gender_city

(80, 4)


array([[1., 1., 0., 0.],
       [1., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 1.],
       [1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],


In [ ]:
# so gender&city are nominal_categorical data , cough can be compared so ordinal
oe = OrdinalEncoder(categories=[['Mild' , 'Strong']])

x_train_cough = oe.fit_transform(x_train[['cough']])
x_test_cough = oe.transform(x_test[['cough']])

x_train_cough.shape


(80, 1)

In [ ]:
# now the age as its remanining
# if not used .values() it willreturn resultin pandas df not numpy array so ,now it hasconv it_into numpy array
x_train_age = x_train.drop(columns=['gender','fever','cough','city']).values
x_test_age = x_test.drop(columns=['gender','fever','cough','city']).values

print(x_train_age)
x_train_age.shape

[[42]
 [34]
 [20]
 [56]
 [42]
 [82]
 [79]
 [33]
 [19]
 [49]
 [65]
 [10]
 [60]
 [12]
 [ 5]
 [49]
 [66]
 [ 6]
 [80]
 [74]
 [25]
 [83]
 [ 8]
 [70]
 [17]
 [82]
 [72]
 [38]
 [19]
 [ 5]
 [22]
 [81]
 [13]
 [65]
 [23]
 [44]
 [73]
 [47]
 [31]
 [34]
 [15]
 [51]
 [68]
 [27]
 [18]
 [46]
 [19]
 [24]
 [60]
 [59]
 [49]
 [71]
 [81]
 [10]
 [20]
 [51]
 [64]
 [54]
 [16]
 [51]
 [34]
 [16]
 [65]
 [64]
 [12]
 [19]
 [23]
 [14]
 [75]
 [80]
 [27]
 [69]
 [42]
 [48]
 [84]
 [ 5]
 [64]
 [83]
 [25]
 [55]]


(80, 1)

In [ ]:
x_train_transformed = np.concatenate((x_train_cough , x_train_fever ,x_train_gender_city , x_train_age),axis=1)
x_test_transformed = np.concatenate((x_test_cough , x_test_fever ,x_test_gender_city , x_test_age),axis=1)

# To horizontally join columns — side by side.

print(x_train_transformed)
x_train_transformed.shape


[[  0.         101.           1.           1.           0.
    0.          42.        ]
 [  1.          98.           1.           0.           1.
    0.          34.        ]
 [  0.         101.           0.           0.           0.
    0.          20.        ]
 [  1.         104.           0.           0.           0.
    0.          56.        ]
 [  1.         100.95833333   0.           0.           0.
    0.          42.        ]
 [  1.         102.           0.           0.           0.
    0.          82.        ]
 [  1.         100.95833333   1.           0.           1.
    0.          79.        ]
 [  1.         102.           0.           1.           0.
    0.          33.        ]
 [  0.         101.           0.           0.           0.
    1.          19.        ]
 [  0.         101.           0.           1.           0.
    0.          49.        ]
 [  0.          99.           1.           0.           0.
    0.          65.        ]
 [  1.          98.           0.

(80, 7)

WORKING WITH COLUMN_TRANSFORMER

In [ ]:
# with columntransformer we can do all inonce ,noneed for seperate applying transformation
# apply different preprocessing steps to different columns of your dataset — all in one step.
from sklearn.compose import ColumnTransformer
transform = ColumnTransformer(transformers = [('tf1' , SimpleImputer() , ['fever'] ) , ( 'tf2' ,OneHotEncoder(drop= 'first' , sparse_output =False) , ['gender','city'] ) , ( 'tf3' ,OrdinalEncoder(categories=[['Mild' , 'Strong']] ) , ['cough'] ) ] , remainder = 'passthrough')


# remainder='passthrough' - means - keep the rest of the columns as they are, don't drop them
# so , now passing reqd. tuples inside the transfomers list with the syntax - Tuple format	('name', transformer, columns)


In [ ]:
transform.fit_transform(x_train)

array([[101.        ,   1.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  42.        ],
       [ 98.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   1.        ,  34.        ],
       [101.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  20.        ],
       [104.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  56.        ],
       [100.95833333,   0.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  42.        ],
       [102.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  82.        ],
       [100.95833333,   1.        ,   0.        ,   1.        ,
          0.        ,   1.        ,  79.        ],
       [102.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   1.        ,  33.        ],
       [101.        ,   0.        ,   0.        ,   0.        ,
          1.    

In [ ]:
transform.fit_transform(x_test).shape

(20, 7)